---
- name: rebuild_module
  ansible.builtin.command:
    cmd: "dkms build -m acer-wmi-battery -v {{ acer_battery_version }}"
  notify: load_module

- name: load_module
  ansible.builtin.shell: |
    modprobe acer_wmi_battery || modprobe acer-wmi-battery
  ignore_errors: true
