---
- name: rebuild_module
  ansible.builtin.command:
    cmd: "dkms build -m acer-wmi-battery -v {{ acer_battery_version }}"
  notify: load_module

- name: load_module
  community.general.modprobe:
    name: acer_wmi_battery
    state: present
  ignore_errors: true
